"""Build the labour market D1 import from the team's cleaned outlook file."""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from datetime import date
from pathlib import Path

# Reuse the proven helpers so both imports produce the same SQL style.
from build_iteration_one_data import (
    insert_many,
    insert_with_release,
    release_statement,
)

ROOT = Path(__file__).resolve().parents[2]
GENERATED_DIR = ROOT / "data" / "generated"
SQL_PATH = GENERATED_DIR / "market_data.sql"
REPORT_PATH = GENERATED_DIR / "market_report.json"
MARKET_CSV = ROOT / "data" / "sources" / "market" / "hireway_role_market_anzsco4.csv"
CATALOG_CSV = ROOT / "data" / "sources" / "iteration-1" / "hireway_role_catalog_osca.csv"

SOURCE_NAME = "Australian labour market outlook"
RELEASE_LABEL = "cleaned_data_2"

STATE_COLUMNS = (
    "vacancies_nsw_jul_2026",
    "vacancies_vic_jul_2026",
    "vacancies_qld_jul_2026",
    "vacancies_sa_jul_2026",
    "vacancies_wa_jul_2026",
    "vacancies_tas_jul_2026",
    "vacancies_nt_jul_2026",
    "vacancies_act_jul_2026",
)
STATES = ("NSW", "VIC", "QLD", "SA", "WA", "TAS", "NT", "ACT")


def as_int(value: str) -> int | None:
    """Round thousands of people into whole-person counts."""

    return round(float(value) * 1000) if value else None


def as_number(value: str) -> float | None:
    return float(value) if value else None


def read_market_rows(path: Path) -> list[dict]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def read_occupation_links(path: Path) -> dict[str, list[str]]:
    """Map every OSCA occupation onto its ANZSCO four-digit groups."""

    links: dict[str, set[str]] = defaultdict(set)
    with path.open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            osca_code = row["osca_code"].strip()
            for mapped in row["mapped_anzsco_codes"].split(";"):
                mapped = mapped.strip()
                if mapped:
                    links[osca_code].add(mapped[:4])
    return {code: sorted(groups) for code, groups in links.items()}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()

    market_rows = read_market_rows(MARKET_CSV)
    occupation_links = read_occupation_links(CATALOG_CSV)

    group_rows: set[tuple[str, str]] = set()
    market_values: list[tuple] = []
    vacancy_values: list[tuple] = []
    link_values: list[tuple[str, str, int]] = []

    for row in market_rows:
        code = row["anzsco4_code"].strip()
        title = row["occupation"].strip()
        group_rows.add((code, title))

        market_values.append(
            (
                code,
                as_int(row["employment_may_2025_thousands"]),
                as_int(row["employment_may_2030_thousands"]),
                as_int(row["employment_may_2035_thousands"]),
                as_number(row["change_5y_pct"]),
                as_number(row["change_10y_pct"]),
                as_number(row["median_weekly_earnings_aud"]),
                as_number(row["vacancies_aust_jul_2026"]),
            )
        )

        for column, state in zip(STATE_COLUMNS, STATES):
            vacancies = as_number(row[column])
            if vacancies is not None:
                vacancy_values.append((code, state, vacancies))

        for occupation_code, groups in occupation_links.items():
            if code in groups:
                link_values.append((occupation_code, code, groups.index(code) == 0))

    # National coverage requires every occupation to reach one market group.
    linked_occupations = {code for code, _, _ in link_values}
    unlinked = sorted(set(occupation_links) - linked_occupations)

    statements = [
        "-- Generated by scripts/data/build_market_data.py.",
        "-- Saved profiles and their skills are never touched by this import.",
        "PRAGMA foreign_keys = ON;",
    ]
    statements += insert_many(
        "data_source",
        ("name", "publisher", "source_url", "licence", "description", "accessed_on"),
        [
            (
                SOURCE_NAME,
                "Jobs and Skills Australia and the Australian Bureau of Statistics",
                "https://www.jobsandskills.gov.au/data/employment-projections",
                "Creative Commons Attribution 4.0 International",
                "Employment projections, earnings and Internet Vacancy Chart "
                "vacancies for Australian occupations. © Commonwealth of Australia.",
                date.today().isoformat(),
            )
        ],
        "(name) DO UPDATE SET publisher = excluded.publisher, "
        "source_url = excluded.source_url, licence = excluded.licence, "
        "description = excluded.description, accessed_on = excluded.accessed_on",
    )
    statements.append(
        release_statement(SOURCE_NAME, RELEASE_LABEL, None, MARKET_CSV)
    )

    # The market refresh replaces its own tables, never personal records.
    statements += [
        "DELETE FROM anzsco4_state_vacancy;",
        "DELETE FROM anzsco4_market;",
        "DELETE FROM occupation_anzsco_map WHERE dataset_release_id IN ("
        "SELECT release.id FROM dataset_release release "
        "JOIN data_source source ON source.id = release.data_source_id "
        f"WHERE source.name = {SOURCE_NAME!r});",
        "DELETE FROM anzsco_group WHERE classification_level = 4;",
    ]

    statements += insert_many(
        "anzsco_group",
        ("code", "title", "classification_level"),
        ((code, title, 4) for code, title in sorted(group_rows)),
        "(code) DO UPDATE SET title = excluded.title, "
        "classification_level = excluded.classification_level",
    )
    statements += insert_with_release(
        "occupation_anzsco_map",
        ("occupation_code", "anzsco_code", "is_primary"),
        link_values,
        SOURCE_NAME,
        RELEASE_LABEL,
        MARKET_CSV.name,
        "(occupation_code, anzsco_code, dataset_release_id) DO UPDATE SET "
        "is_primary = excluded.is_primary, "
        "dataset_release_id = excluded.dataset_release_id",
    )
    statements += insert_with_release(
        "anzsco4_market",
        (
            "anzsco4_code",
            "employed_may_2025",
            "employed_may_2030",
            "employed_may_2035",
            "change_5y_percent",
            "change_10y_percent",
            "median_weekly_earnings",
            "vacancies_total",
        ),
        market_values,
        SOURCE_NAME,
        RELEASE_LABEL,
        MARKET_CSV.name,
        "(anzsco4_code) DO UPDATE SET "
        "employed_may_2025 = excluded.employed_may_2025, "
        "employed_may_2030 = excluded.employed_may_2030, "
        "employed_may_2035 = excluded.employed_may_2035, "
        "change_5y_percent = excluded.change_5y_percent, "
        "change_10y_percent = excluded.change_10y_percent, "
        "median_weekly_earnings = excluded.median_weekly_earnings, "
        "vacancies_total = excluded.vacancies_total, "
        "dataset_release_id = excluded.dataset_release_id",
    )
    statements += insert_with_release(
        "anzsco4_state_vacancy",
        ("anzsco4_code", "state_code", "vacancy_count"),
        vacancy_values,
        SOURCE_NAME,
        RELEASE_LABEL,
        MARKET_CSV.name,
        "(anzsco4_code, state_code, dataset_release_id) DO UPDATE SET "
        "vacancy_count = excluded.vacancy_count, "
        "dataset_release_id = excluded.dataset_release_id",
    )

    SQL_PATH.parent.mkdir(parents=True, exist_ok=True)
    SQL_PATH.write_text("\n".join(statements) + "\n", encoding="utf-8")

    report = {
        "anzsco4_groups": len(group_rows),
        "market_rows": len(market_values),
        "state_vacancy_rows": len(vacancy_values),
        "occupation_links": len(link_values),
        "occupations_without_market_link": unlinked,
        "missing_market_projection_rows": sum(
            1
            for row in market_values
            if row[1] is None or row[2] is None or row[3] is None
        ),
    }
    REPORT_PATH.write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
